### ISSUE TITLE
Problème de dépendance Yarn

### ISSUE THREAD

**Issue by Stax2069** [BigChicChicken/NW_TimerBot#2]
Bon j'ai plusieurs soucis mais je vais commencer par celui-la.
Quand j'installe les dépendances de yarn j'ai ce message:
![image](https://user-images.githubusercontent.com/116718044/197991910-e0a1e414-f103-48ec-8aa7-1bebc7e4c87e.png)
une idée ?

**Comment by BigChicChicken** [comment]
> Bon j'ai plusieurs soucis mais je vais commencer par celui-la. Quand j'installe les dépendances de yarn j'ai ce message: ![image](https://user-images.githubusercontent.com/116718044/197991910-e0a1e414-f103-48ec-8aa7-1bebc7e4c87e.png) une idée ?

Tu es sur quel OS (Windows, Linux, Mac) ?

**Comment by Stax2069** [comment]
Windows 10

**Comment by BigChicChicken** [comment]
> Windows 10

Tu as fait le prérequis ?
https://github.com/BigChicChicken/NW_TimerBot#prerequisite

**Comment by Stax2069** [comment]
je ne sais pas comment mettre [Install FFmpeg](https://ffmpeg.org/) je ne sais pas quoi faire du dossier téléchargé.

pour le reste c'est ok

**Comment by BigChicChicken** [comment]
> je ne sais pas comment mettre [Install FFmpeg](https://ffmpeg.org/) je ne sais pas quoi faire du dossier téléchargé.
> 
> pour le reste c'est ok

https://www.wikihow.com/Install-FFmpeg-on-Windows

**Comment by Stax2069** [comment]
Ok pour ffmpeg c'est installé. merci

**Comment by Stax2069** [comment]
il se passe pas grand chose quand je lance la commande yarn prod.je voisq les trois bot qui se connecte à mon discord mais rien de plus.

**Comment by BigChicChicken** [comment]
> il se passe pas grand chose quand je lance la commande yarn prod.je voisq les trois bot qui se connecte à mon discord mais rien de plus.

- Eteint le bot.
- Vide le dossier "logs" à la racine du projet.
- Relance le bot (yarn prod).
- Si le bot a bien créer les bouttons, appui sur "Start" (Aperçu des boutons : https://github.com/BigChicChicken/NW_TimerBot#usage).
- Attend 1 minute (afin de lui laisser le temps d'annoncé un respawn).
- Copie/Colle le contenu du fichier log du bot ici afin qu'on puisse voir les étapes faites par lui.

**Comment by Stax2069** [comment]
j'ai un message d'erreur au moment ou il tente de jouer un son 
![image](https://user-images.githubusercontent.com/116718044/198001837-041ba9d1-7589-49c8-8c9c-b73224399502.png)

**Comment by BigChicChicken** [comment]
> j'ai un message d'erreur au moment ou il tente de jouer un son ![image](https://user-images.githubusercontent.com/116718044/198001837-041ba9d1-7589-49c8-8c9c-b73224399502.png)

Il te manque sodium, normalement, il vient avec le windows-build-tools...

On va essayé de refaire cette étape, [lance une console de commande en mode administrateur](https://www.pcastuces.com/pratique/astuces/4150.htm) et exécute la commande suivante:
`yarn global add windows-build-tools --production --vs2015 --debug`

Relance le bot et si le message d'erreur lié à sodium s'affiche toujours, essaye les commandes suivantes à la racine du dossier du projet:
`yarn config set msvs_version 2015 --global`
`yarn add sodium`

**Comment by Stax2069** [comment]
j'ai ça comme message 
![image](https://user-images.githubusercontent.com/116718044/198011360-72cecfdc-d84b-4572-a00d-48e57dd6c1cb.png)

**Comment by BigChicChicken** [comment]
> j'ai ça comme message ![image](https://user-images.githubusercontent.com/116718044/198011360-72cecfdc-d84b-4572-a00d-48e57dd6c1cb.png)

Je n'était pas au courant de cette nouveauté chez yarn, lance à la place:
`yarn dlx windows-build-tools --production --vs2015 --debug`

**Comment by Stax2069** [comment]
pour les deux autres commande ça donne ça 
![image](https://user-images.githubusercontent.com/116718044/198012475-bbbd9f9e-07d0-4082-ab4a-76ae2d3d6e1d.png)

**Comment by BigChicChicken** [comment]
> j'ai ça comme message ![image](https://user-images.githubusercontent.com/116718044/198011360-72cecfdc-d84b-4572-a00d-48e57dd6c1cb.png)

Je n'était pas au courant de cette nouveauté chez yarn, lance à la place:
`yarn dlx windows-build-tools --production --vs2015 --debug`

**Comment by Stax2069** [comment]
![image](https://user-images.githubusercontent.com/116718044/198013367-ef74fdde-be4b-4279-91b4-4674f56e99ef.png)

**Comment by Stax2069** [comment]
j'ai pas tout compris mais je crois que ça a pas marché xD

**Comment by Stax2069** [comment]
depuis que j'ai rentré ça 

yarn config set msvs_version 2015 --global
yarn add sodium

j'ai plus les même erreurs j'ai ça plus 2000 lignes d'erreurs environ xD
![image](https://user-images.githubusercontent.com/116718044/198015420-d68f9c60-ea6d-4a5c-adba-4085984d331a.png)

**Comment by Stax2069** [comment]
AHHHHHHHHHHHHHHHHHHHH ça marche !!!!!!
j'ai juste ajouté cette commande
npm install sodium-universal
MERCI  à toi !!!!!

**Comment by BigChicChicken** [comment]
> AHHHHHHHHHHHHHHHHHHHH ça marche !!!!!! j'ai juste ajouté cette commande npm install sodium-universal MERCI à toi !!!!!

Super !!!
J'était en train d'installer un windows neuf pour faire un tuto étape par étape, je le rajouterai à la doc.

**Comment by Stax2069** [comment]
Au niveau des timers de respawn ils sont bon tu as testé ?

**Comment by BigChicChicken** [comment]
> Au niveau des timers de respawn ils sont bon tu as testé ?

Ils étaient bon en Août 2022, depuis je ne joue plus à NW et donc je ne suis pas au courant s'il y a eu des changements...
Mais si c'est le cas, il faut juste modifier les valeurs dans le fichier `src/config.js`.

Attention sur deux points:
- L'horloge du bot est celui de ton système, il faut donc que ton horloge windows soit bien à l'heure.
- Et à l'époque pendant certaines war, ils y avaient des désynchronisations entre le bot et NW, mais le problème venait des serveurs de NW, donc il peut arrivé que 2-3 timer aléatoire soit faussé de manière ponctuelle (il n'y a aucune solution pour palié à ce problème).

**Comment by Stax2069** [comment]
Du coup je viens de tester le timer de respawn, il se lance meme sans avoir cliqué sur strat. 

Je m'explique : j'ai activé le bot et 15 minutes après j'ai cliqué sur "start" du bot1 il arrive dans chan et me dit 10s puis après avoir dit respawning il dit 50s .(ça devrait etre plus rapide en début de war) 

Donc tu me confirmes qu'il faut lancer la commande  yarn prod  pile au moment du début de la guerre ? quand le timer de préparation est à 0 ? (et du coup cliquer sur start après pour avoir l'audio)

**Comment by BigChicChicken** [comment]
> Du coup je viens de tester le timer de respawn, il se lance meme sans avoir cliqué sur strat.
> 
> Je m'explique : j'ai activé le bot et 15 minutes après j'ai cliqué sur "start" du bot1 il arrive dans chan et me dit 10s puis après avoir dit respawning il dit 50s .(ça devrait etre plus rapide en début de war)
> 
> Donc tu me confirmes qu'il faut lancer la commande yarn prod pile au moment du début de la guerre ? quand le timer de préparation est à 0 ? (et du coup cliquer sur start après pour avoir l'audio)

Pour information:

`yarn prod` => Sert à lancer le bot, le bot ne fait rien, il ne fait qu'attendre une action sur les boutons.
`Appuie sur le bouton Start` => Le bot commence le calcul, décompte et annonce les timers dans un channel vocal.
`Appuie sur le bouton Stop` => Le bot arrête le décompte et se déconnecte du channel vocal.
`Appuie sur le bouton ?` => Le bot envoi un message privé avec l'heure de ton système et une heure trouvé sur internet pour savoir si tu es synchronisé.

Pour les war étant donner qu'ils sont à heure fixe (ex: 20H00, 20H30, 21H00, 21H30), le bot s'adapte automatiquement peu importe l'heure à laquelle tu appuis sur le bouton "Start".
Par exemple si tu le lances 19H12 (donc 12minutes après le début de la war), il calculera que tu es dans la war de 19H00 -> 19H30 et va te donner les bons timer à l'instant T donc les timers à 12 minutes.

**Comment by Stax2069** [comment]
AAAAAAAAAAAAHHHHHH ok c'est super du coup !!! 
Merci pour ton travail et le temps que tu m'as consacré !!!
En espérant que l'heure de mon pc sera la même que les serveur new world !
j'ai testé et je suis bien à la même que internet .
Merci encore !

**Comment by BigChicChicken** [comment]
> AAAAAAAAAAAAHHHHHH ok c'est super du coup !!! Merci pour ton travail et le temps que tu m'as consacré !!! En espérant que l'heure de mon pc sera la même que les serveur new world ! j'ai testé et je suis bien à la même que internet . Merci encore !

Pas de soucis et bonne WAR ;)

9673823f88e659e5968609fd41ef83b0ae041f8c
a37835b33c48631a42c722a80b9216d475d8692c
f6faa52b7f68b0582b389e5d3b86f03f351ad0dc
