### ISSUE TITLE
Bot stops calling

### ISSUE THREAD

**Issue by dakandi** [BigChicChicken/NW_TimerBot#5]
Hello,

since yesterday the bot stops calling respawn times after the 1st wave.

Can this problem be caused from my internet connection or my provider blocking it somehow?

**Comment by BigChicChicken** [comment]
Hi,
Good question... Did you get logs in the terminal ?

**Comment by dakandi** [comment]
i got this only once
![timerbot](https://user-images.githubusercontent.com/126904329/222830052-4640a442-ba4f-46b0-a902-0cbbacfac5f4.png)

tried a couple of times again after this error message but did not get it agian.

always same behavior after start: 1st wave counts down to respawn and after 1st wave bot stops to call.

Maybe I need to open some ports and do port forwarding? I would be surprised, because it worked fine for months.

**Comment by BigChicChicken** [comment]
OK, you have the same problem as this issue => https://github.com/BigChicChicken/NW_TimerBot/issues/3
The problem come from your proxy, but I add some tests to prevent crashes if the application cannot call the api to get the time from the internet.
I invite you to download/clone this changes.

**Comment by dakandi** [comment]
already downloaded that changes before i opend this issue here :/

I run the bot at this moment, same behavior again, 1st wave counts down to respawn and after 1st wave bot stops to call.
![image](https://user-images.githubusercontent.com/126904329/223118287-0a29d22f-d49a-40a8-a409-7ea8c7f7096d.png)

also tried with an vpn but no luck

**Comment by coubo** [comment]
Yea, I confirm that the bot stops calling after the 1st wave.
The bot also freeze in discord and does not respond to anything and cannot be disconnected if we click on the stop button.

Regarding the fetcherror, I tried with another time api and it solved it.

**Comment by dodigamestudios** [comment]
> 

hello whats the another time api ? to solve ?

**Comment by dakandi** [comment]
> Yea, I confirm that the bot stops calling after the 1st wave. The bot also freeze in discord and does not respond to anything and cannot be disconnected if we click on the stop button.
> 
> Regarding the fetcherror, I tried with another time api and it solved it.

so does this mean, the bug to stop calling got introduced with the last update? https://github.com/BigChicChicken/NW_TimerBot/commit/2d9552ef99bbc5f78d768b160328214a27093098

**Comment by dodigamestudios** [comment]
> > Yea, I confirm that the bot stops calling after the 1st wave. The bot also freeze in discord and does not respond to anything and cannot be disconnected if we click on the stop button.
> > Regarding the fetcherror, I tried with another time api and it solved it.
> 
> so does this mean, the bug to stop calling got introduced with the last update? [2d9552e](https://github.com/BigChicChicken/NW_TimerBot/commit/2d9552ef99bbc5f78d768b160328214a27093098)

yes stopping after first call and when clicking stop button etc not working anymore

**Comment by coubo** [comment]
Hello, I found the fix :

adding this.configureNetworking(); on the line 1361 of this file located at node_modules/@discordjs/voice/dist/index.js

**Comment by coubo** [comment]
Fix #2 : https://github.com/discordjs/discord.js/issues/9185#issuecomment-1452514375

**Comment by BigChicChicken** [comment]
I invite you to download/clone new changes.
